#!/usr/bin/env python3
"""
Pipeline generated by Meta Llama 3.1 70B via AWS Bedrock.
Minimal fixes applied to make it runnable:
  - Load PBMC data via scanpy.datasets (Llama assumed files exist)
  - Fix boto3 Session syntax (Llama used wrong keyword arg)
  - Fill in the memory/time tracking Llama left as '...omitted for brevity'
  - Use pbmc68k_reduced as the well-characterized reference (Llama said 'human_primary_cell_atlas.h5ad')
  - Create marker_genes dict inline (Llama said 'load from marker_genes.csv')
  - Fix zero_shot logic (Llama's np.argmax returned gene index, not cell assignment)
Llama's algorithmic choices are preserved:
  - Zero-shot: average expression of known marker genes per cluster
  - Reference mapping: dot-product similarity between cells and reference centroids
  - No LLM API call (Llama did not generate one)
Results stored in results_llama/ to avoid overwriting Claude pipeline results.
"""

import boto3
import os
import time
import tracemalloc
import pandas as pd
import numpy as np
import scanpy as sc
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import issparse
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    f1_score, cohen_kappa_score,
)

# ── Config (from Llama's script) ──────────────────────────────────────────────
AWS_PROFILE = "chewu-scripps"
S3_BUCKET   = "scrippsresearch-chewu-hackathon"
RESULTS_DIR = "results_llama"
os.makedirs(f"{RESULTS_DIR}/plots",      exist_ok=True)
os.makedirs(f"{RESULTS_DIR}/evaluation", exist_ok=True)

# Llama used boto3.client('s3', profile_name=...) which is wrong syntax.
# Fixed: profile goes in Session.
s3 = boto3.Session(profile_name=AWS_PROFILE,
                   region_name="us-west-2").client("s3")

print("=" * 60)
print("  Llama-generated PBMC Annotation Pipeline")
print("=" * 60)

# ── Load PBMC dataset ─────────────────────────────────────────────────────────
# Llama assumed pbmc_10k_protein_v3.h5ad; using scanpy.datasets.pbmc3k() instead.
print("\nLoading PBMC dataset...")
adata     = sc.datasets.pbmc3k()
adata_ref_gt = sc.datasets.pbmc3k_processed()   # ground truth only

# Save ground truth (existing annotation Llama said to compare against)
gt = adata_ref_gt.obs[["louvain"]].copy()
gt.index.name = "cell_barcode"
gt = gt.rename(columns={"louvain": "ground_truth"})
gt.to_csv(f"{RESULTS_DIR}/ground_truth_labels.csv")
print(f"Ground truth cell types: {sorted(gt['ground_truth'].unique())}")

# Standard preprocessing (needed before Llama's annotation steps)
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
adata.var["mt"] = adata.var_names.str.startswith("MT-")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], percent_top=None,
                            log1p=False, inplace=True)
adata = adata[adata.obs.n_genes_by_counts < 2500].copy()
adata = adata[adata.obs.pct_counts_mt < 5].copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
adata.raw = adata
sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
adata_hvg = adata[:, adata.var.highly_variable].copy()
sc.pp.scale(adata_hvg, max_value=10)
sc.tl.pca(adata_hvg, svd_solver="arpack")
sc.pp.neighbors(adata_hvg, n_neighbors=10, n_pcs=40)
sc.tl.umap(adata_hvg)
sc.tl.leiden(adata_hvg, resolution=0.5, key_added="leiden")
adata.obs["leiden"] = adata_hvg.obs["leiden"]
adata.obsm["X_umap"] = adata_hvg.obsm["X_umap"]
shared = adata.obs_names.intersection(gt.index)
adata.obs["ground_truth"] = "Unknown"
adata.obs.loc[shared, "ground_truth"] = gt.loc[shared, "ground_truth"]
print(f"Cells: {adata.n_obs}  Clusters: {adata.obs['leiden'].nunique()}")

# ── Marker genes (Llama said 'load from marker_genes.csv') ───────────────────
# Using well-known PBMC marker genes from literature.
MARKER_GENES = {
    "CD4 T cells":        ["CD3D", "CD3E", "CD4", "IL7R", "CCR7", "LTB", "LDHB"],
    "CD8 T cells":        ["CD8A", "CD8B", "NKG7", "GZMB", "GZMA", "PRF1", "CST7"],
    "NK cells":           ["GNLY", "NKG7", "KLRD1", "NCAM1", "FCGR3A", "KLRB1"],
    "B cells":            ["MS4A1", "CD79A", "CD79B", "CD19", "BANK1"],
    "CD14+ Monocytes":    ["CD14", "LYZ", "S100A9", "S100A8", "CST3", "FCN1"],
    "FCGR3A+ Monocytes":  ["FCGR3A", "MS4A7", "IFITM3", "CFD", "LST1"],
    "Dendritic cells":    ["FCER1A", "CST3", "CLEC10A", "HLA-DQA1", "HLA-DRA"],
    "Megakaryocytes":     ["PPBP", "PF4", "GP9", "GNG11", "SDPR"],
}

# Save marker genes CSV (as Llama expected it to exist)
rows = [(ct, g) for ct, genes in MARKER_GENES.items() for g in genes]
pd.DataFrame(rows, columns=["cell_type", "gene"]).to_csv(
    f"{RESULTS_DIR}/marker_genes.csv", index=False)

# ── Method 1: Zero-Shot Annotation (Llama's approach) ─────────────────────────
# Llama: "Calculate the average expression of marker genes for each cell,
#          assign cells to the cell type with the highest average expression."
# Fixed: apply per cluster (not per cell returning gene index).
print("\n── Method 1: Zero-Shot Annotation (Llama) ──")
t0_zs = time.time()
tracemalloc.start()

def zero_shot_annotation(adata, marker_genes):
    cluster_annotations = {}
    for cluster in sorted(adata.obs["leiden"].unique(), key=int):
        cluster_mask = adata.obs["leiden"] == cluster
        cluster_data = adata[cluster_mask]
        scores = {}
        for cell_type, genes in marker_genes.items():
            valid_genes = [g for g in genes if g in adata.var_names]
            if valid_genes:
                X = cluster_data[:, valid_genes].X
                avg_expr = (X.toarray() if issparse(X) else X).mean()
                scores[cell_type] = float(avg_expr)
        cluster_annotations[cluster] = max(scores, key=scores.get)
    return cluster_annotations

cluster_annotations = zero_shot_annotation(adata, MARKER_GENES)
print("Zero-shot cluster annotations:")
for c, ct in sorted(cluster_annotations.items(), key=lambda x: int(x[0])):
    print(f"  Cluster {c}: {ct}")

# Expand cluster → cell level
adata.obs["zero_shot_annotation"] = adata.obs["leiden"].map(cluster_annotations)
zs_out = adata.obs[["leiden", "zero_shot_annotation"]].copy()
zs_out.index.name = "cell_barcode"
zs_out.to_csv(f"{RESULTS_DIR}/zero_shot_annotations.csv")
s3.upload_file(f"{RESULTS_DIR}/zero_shot_annotations.csv",
               S3_BUCKET, f"results_llama/zero_shot_annotations.csv")

elapsed_zs = time.time() - t0_zs
cur, peak_zs = tracemalloc.get_traced_memory()
tracemalloc.stop()
print(f"  Time: {elapsed_zs:.1f}s  |  Peak mem: {peak_zs/1024**2:.1f} MB")

pd.DataFrame([{"step":"zero_shot_llama_approach","wall_time_sec":round(elapsed_zs,2),
               "peak_mem_mb":round(peak_zs/1024**2,1)}]).to_csv(
    f"{RESULTS_DIR}/timing_zero_shot.csv", index=False)

# ── Method 2: Reference Mapping (Llama's dot-product approach) ────────────────
# Llama: "Calculate similarity between PBMC cells and reference cells (dot product),
#          assign cells to the cell type with the highest similarity."
# Reference: pbmc68k_reduced (10x Genomics 68k PBMC — different from pbmc3k).
print("\n── Method 2: Reference Mapping (Llama dot-product) ──")
t0_ref = time.time()
tracemalloc.start()

# Load well-characterized reference dataset (Llama said 'human_primary_cell_atlas.h5ad')
ref = sc.datasets.pbmc68k_reduced()
print(f"Reference dataset: pbmc68k_reduced  shape={ref.shape}")
print(f"Reference cell types: {sorted(ref.obs['bulk_labels'].unique())}")

def reference_mapping(adata, reference_adata, ref_label_col="bulk_labels"):
    """Llama's dot-product similarity reference mapping."""
    # Find common genes
    common_genes = adata.var_names.intersection(reference_adata.var_names)
    print(f"  Common genes: {len(common_genes)}")

    # Compute reference centroids (average expression per cell type)
    ref_sub = reference_adata[:, common_genes]
    cell_type_centroids = {}
    for cell_type in ref_sub.obs[ref_label_col].unique():
        mask = ref_sub.obs[ref_label_col] == cell_type
        X = ref_sub[mask].X
        centroid = np.array(X.toarray() if issparse(X) else X).mean(axis=0)
        cell_type_centroids[cell_type] = centroid

    # For each test cell, compute dot-product similarity with each centroid
    test_sub = adata[:, common_genes]
    annotations = []
    batch = 200
    for start in range(0, test_sub.n_obs, batch):
        X_batch = test_sub[start:start+batch].X
        if issparse(X_batch):
            X_batch = X_batch.toarray()
        for cell_vec in X_batch:
            sims = {ct: float(np.dot(cell_vec, centroid))
                    for ct, centroid in cell_type_centroids.items()}
            annotations.append(max(sims, key=sims.get))
    return annotations

ref_annotations = reference_mapping(adata, ref)
adata.obs["reference_annotation"] = ref_annotations

ref_out = adata.obs[["leiden", "reference_annotation"]].copy()
ref_out.index.name = "cell_barcode"
ref_out.to_csv(f"{RESULTS_DIR}/reference_annotations.csv")
s3.upload_file(f"{RESULTS_DIR}/reference_annotations.csv",
               S3_BUCKET, f"results_llama/reference_annotations.csv")

print("Reference annotation distribution:")
print(adata.obs["reference_annotation"].value_counts().to_string())

elapsed_ref = time.time() - t0_ref
cur, peak_ref = tracemalloc.get_traced_memory()
tracemalloc.stop()
print(f"  Time: {elapsed_ref:.1f}s  |  Peak mem: {peak_ref/1024**2:.1f} MB")

pd.DataFrame([{"step":"reference_mapping_llama_approach","wall_time_sec":round(elapsed_ref,2),
               "peak_mem_mb":round(peak_ref/1024**2,1)}]).to_csv(
    f"{RESULTS_DIR}/timing_reference.csv", index=False)

# ── UMAP plots ────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for ax, col, title in zip(axes,
    ["ground_truth", "zero_shot_annotation", "reference_annotation"],
    ["Ground Truth", "Zero-Shot (Llama)", "Reference Mapping (Llama dot-product)"]):
    sc.pl.umap(adata, color=col, title=title, ax=ax, show=False,
               legend_loc="right margin" if ax is axes[2] else "on data",
               legend_fontsize=7)
fig.tight_layout()
fig.savefig(f"{RESULTS_DIR}/plots/umap_three_way.png", dpi=150)
plt.close()

# ── Label harmonisation ───────────────────────────────────────────────────────
# Map all label spaces → common canonical (same as Claude pipeline for fair comparison)
GT_MAP = {
    "CD4 T cells": "CD4 T", "CD8 T cells": "CD8 T", "NK cells": "NK",
    "B cells": "B", "CD14+ Monocytes": "CD14 Mono",
    "FCGR3A+ Monocytes": "FCGR3A Mono", "Dendritic cells": "DC",
    "Megakaryocytes": "Platelet",
}
ZS_MAP = {
    "CD4 T cells": "CD4 T", "CD8 T cells": "CD8 T", "NK cells": "NK",
    "B cells": "B", "CD14+ Monocytes": "CD14 Mono",
    "FCGR3A+ Monocytes": "FCGR3A Mono", "Dendritic cells": "DC",
    "Megakaryocytes": "Platelet",
}
# Reference: pbmc68k bulk_labels → canonical
REF_MAP = {
    "CD4+/CD45RA+/CD25- Naive T": "CD4 T",
    "CD4+/CD45RO+ Memory":        "CD4 T",
    "CD4+/CD25 T Reg":            "CD4 T",
    "CD8+ Cytotoxic T":           "CD8 T",
    "CD8+/CD45RA+ Naive Cytotoxic": "CD8 T",
    "CD56+ NK":                   "NK",
    "CD19+ B":                    "B",
    "CD14+ Monocyte":             "CD14 Mono",
    "Dendritic":                  "DC",
    "CD34+":                      "Unknown",
}

def safe_map(series, mapping):
    """Map a pandas Series (possibly Categorical) using a dict, returning a plain str Series."""
    return pd.Series(
        [mapping.get(str(v), "Unknown") for v in series],
        index=series.index, dtype=str
    )

adata.obs["gt_canonical"]  = safe_map(adata.obs["ground_truth"],         GT_MAP)
adata.obs["zs_canonical"]  = safe_map(adata.obs["zero_shot_annotation"],  ZS_MAP)
adata.obs["ref_canonical"] = safe_map(adata.obs["reference_annotation"],  REF_MAP)

# ── Metrics (Llama: "calculate accuracy, precision, recall, F1, confusion matrix") ──
def calc_metrics(pred_col, label):
    df = adata.obs[["gt_canonical", pred_col]].copy()
    df = df[(df["gt_canonical"] != "Unknown") & (df[pred_col] != "Unknown")]
    y_t, y_p = df["gt_canonical"].tolist(), df[pred_col].tolist()
    n = len(y_t)
    acc = accuracy_score(y_t, y_p)
    wf1 = f1_score(y_t, y_p, average="weighted", zero_division=0)
    mf1 = f1_score(y_t, y_p, average="macro",    zero_division=0)
    kap = cohen_kappa_score(y_t, y_p)
    rep = classification_report(y_t, y_p, output_dict=True, zero_division=0)
    per = (pd.DataFrame(rep).T.iloc[:-3]
           .rename(columns={"support":"n_cells"})
           .assign(n_cells=lambda d: d["n_cells"].astype(int)))
    print(f"\n── {label} ──")
    print(f"  Cells : {n}/{len(adata)}  ({100*n/len(adata):.1f}%)")
    print(f"  Accuracy    : {acc:.4f}  ({100*acc:.1f}%)")
    print(f"  Macro F1    : {mf1:.4f}")
    print(f"  Weighted F1 : {wf1:.4f}")
    print(f"  Kappa       : {kap:.4f}")
    print(per[["precision","recall","f1-score","n_cells"]].to_string())
    return dict(method=label, n_cells=n, accuracy=acc,
                macro_f1=mf1, weighted_f1=wf1, cohen_kappa=kap,
                per_class=per, y_true=y_t, y_pred=y_p)

print("\n── Evaluation ──")
m_zs  = calc_metrics("zs_canonical",  "Zero-Shot (Llama marker-gene scoring)")
m_ref = calc_metrics("ref_canonical", "Reference Mapping (Llama dot-product, pbmc68k ref)")

# ── Confusion matrices ────────────────────────────────────────────────────────
def plot_conf(y_t, y_p, title, path):
    labels = sorted(set(y_t) | set(y_p))
    cm = confusion_matrix(y_t, y_p, labels=labels, normalize="true")
    fig, ax = plt.subplots(figsize=(9, 8))
    sns.heatmap(cm, annot=True, fmt=".2f", cmap="Blues",
                xticklabels=labels, yticklabels=labels,
                linewidths=0.5, ax=ax, vmin=0, vmax=1, annot_kws={"size": 9})
    ax.set_xlabel("Ground Truth"); ax.set_ylabel("Predicted")
    ax.set_title(title, fontsize=12)
    ax.tick_params(axis="x", rotation=35, labelsize=9)
    ax.tick_params(axis="y", rotation=0,  labelsize=9)
    fig.tight_layout(); fig.savefig(path, dpi=150); plt.close()

plot_conf(m_zs["y_true"],  m_zs["y_pred"],
          "Llama Zero-Shot — Confusion Matrix",
          f"{RESULTS_DIR}/evaluation/confusion_zero_shot.png")
plot_conf(m_ref["y_true"], m_ref["y_pred"],
          "Llama Reference Mapping — Confusion Matrix",
          f"{RESULTS_DIR}/evaluation/confusion_reference.png")

# ── Summary CSV ───────────────────────────────────────────────────────────────
summary = pd.DataFrame([
    {k: v for k, v in m.items() if k not in ("per_class","y_true","y_pred")}
    for m in (m_zs, m_ref)
])
summary.to_csv(f"{RESULTS_DIR}/evaluation/metrics_summary.csv", index=False)
m_zs["per_class"].to_csv(f"{RESULTS_DIR}/evaluation/per_class_zero_shot.csv")
m_ref["per_class"].to_csv(f"{RESULTS_DIR}/evaluation/per_class_reference.csv")

# Combined timing
timing = pd.concat([
    pd.read_csv(f"{RESULTS_DIR}/timing_zero_shot.csv"),
    pd.read_csv(f"{RESULTS_DIR}/timing_reference.csv"),
])
timing.to_csv(f"{RESULTS_DIR}/evaluation/timing_summary.csv", index=False)
print(f"\n── Resource Usage ──\n{timing[['step','wall_time_sec','peak_mem_mb']].to_string(index=False)}")

# ── Upload all results to S3 ──────────────────────────────────────────────────
import glob
for fpath in glob.glob(f"{RESULTS_DIR}/**/*", recursive=True):
    if os.path.isfile(fpath):
        s3_key = fpath.replace(RESULTS_DIR, "results_llama")
        s3.upload_file(fpath, S3_BUCKET, s3_key)
        print(f"  Uploaded → s3://{S3_BUCKET}/{s3_key}")

print(f"\n{'='*60}")
print("  FINAL RESULTS (Llama-generated pipeline)")
print(f"{'='*60}")
print(summary[["method","n_cells","accuracy","macro_f1","weighted_f1","cohen_kappa"]].to_string(index=False))
print(f"\nAll results → {RESULTS_DIR}/  and  s3://{S3_BUCKET}/results_llama/")
